//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE.WSConversorFecha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WSConversorFecha", ConfigurationName="WSConversorFecha.WSConversorFechaSoap")]
    public interface WSConversorFechaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres WSConversorFecha no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="WSConversorFecha/ConvertirFecha", ReplyAction="*")]
        FE.WSConversorFecha.ConvertirFechaResponse ConvertirFecha(FE.WSConversorFecha.ConvertirFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSConversorFecha/ConvertirFecha", ReplyAction="*")]
        System.Threading.Tasks.Task<FE.WSConversorFecha.ConvertirFechaResponse> ConvertirFechaAsync(FE.WSConversorFecha.ConvertirFechaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirFecha", Namespace="WSConversorFecha", Order=0)]
        public FE.WSConversorFecha.ConvertirFechaRequestBody Body;
        
        public ConvertirFechaRequest() {
        }
        
        public ConvertirFechaRequest(FE.WSConversorFecha.ConvertirFechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSConversorFecha")]
    public partial class ConvertirFechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public ConvertirFechaRequestBody() {
        }
        
        public ConvertirFechaRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirFechaResponse", Namespace="WSConversorFecha", Order=0)]
        public FE.WSConversorFecha.ConvertirFechaResponseBody Body;
        
        public ConvertirFechaResponse() {
        }
        
        public ConvertirFechaResponse(FE.WSConversorFecha.ConvertirFechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSConversorFecha")]
    public partial class ConvertirFechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ConvertirFechaResult;
        
        public ConvertirFechaResponseBody() {
        }
        
        public ConvertirFechaResponseBody(System.DateTime ConvertirFechaResult) {
            this.ConvertirFechaResult = ConvertirFechaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSConversorFechaSoapChannel : FE.WSConversorFecha.WSConversorFechaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSConversorFechaSoapClient : System.ServiceModel.ClientBase<FE.WSConversorFecha.WSConversorFechaSoap>, FE.WSConversorFecha.WSConversorFechaSoap {
        
        public WSConversorFechaSoapClient() {
        }
        
        public WSConversorFechaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSConversorFechaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSConversorFechaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSConversorFechaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE.WSConversorFecha.ConvertirFechaResponse FE.WSConversorFecha.WSConversorFechaSoap.ConvertirFecha(FE.WSConversorFecha.ConvertirFechaRequest request) {
            return base.Channel.ConvertirFecha(request);
        }
        
        public System.DateTime ConvertirFecha(string fecha) {
            FE.WSConversorFecha.ConvertirFechaRequest inValue = new FE.WSConversorFecha.ConvertirFechaRequest();
            inValue.Body = new FE.WSConversorFecha.ConvertirFechaRequestBody();
            inValue.Body.fecha = fecha;
            FE.WSConversorFecha.ConvertirFechaResponse retVal = ((FE.WSConversorFecha.WSConversorFechaSoap)(this)).ConvertirFecha(inValue);
            return retVal.Body.ConvertirFechaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE.WSConversorFecha.ConvertirFechaResponse> FE.WSConversorFecha.WSConversorFechaSoap.ConvertirFechaAsync(FE.WSConversorFecha.ConvertirFechaRequest request) {
            return base.Channel.ConvertirFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE.WSConversorFecha.ConvertirFechaResponse> ConvertirFechaAsync(string fecha) {
            FE.WSConversorFecha.ConvertirFechaRequest inValue = new FE.WSConversorFecha.ConvertirFechaRequest();
            inValue.Body = new FE.WSConversorFecha.ConvertirFechaRequestBody();
            inValue.Body.fecha = fecha;
            return ((FE.WSConversorFecha.WSConversorFechaSoap)(this)).ConvertirFechaAsync(inValue);
        }
    }
}
