//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE.WSDivisas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="InfoDivisas", ConfigurationName="WSDivisas.WSDivisasSoap")]
    public interface WSDivisasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento moneda del espacio de nombres InfoDivisas no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="InfoDivisas/RecuperarCotizacion", ReplyAction="*")]
        FE.WSDivisas.RecuperarCotizacionResponse RecuperarCotizacion(FE.WSDivisas.RecuperarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="InfoDivisas/RecuperarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<FE.WSDivisas.RecuperarCotizacionResponse> RecuperarCotizacionAsync(FE.WSDivisas.RecuperarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperarCotizacion", Namespace="InfoDivisas", Order=0)]
        public FE.WSDivisas.RecuperarCotizacionRequestBody Body;
        
        public RecuperarCotizacionRequest() {
        }
        
        public RecuperarCotizacionRequest(FE.WSDivisas.RecuperarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="InfoDivisas")]
    public partial class RecuperarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string moneda;
        
        public RecuperarCotizacionRequestBody() {
        }
        
        public RecuperarCotizacionRequestBody(string moneda) {
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperarCotizacionResponse", Namespace="InfoDivisas", Order=0)]
        public FE.WSDivisas.RecuperarCotizacionResponseBody Body;
        
        public RecuperarCotizacionResponse() {
        }
        
        public RecuperarCotizacionResponse(FE.WSDivisas.RecuperarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="InfoDivisas")]
    public partial class RecuperarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecuperarCotizacionResult;
        
        public RecuperarCotizacionResponseBody() {
        }
        
        public RecuperarCotizacionResponseBody(string RecuperarCotizacionResult) {
            this.RecuperarCotizacionResult = RecuperarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDivisasSoapChannel : FE.WSDivisas.WSDivisasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDivisasSoapClient : System.ServiceModel.ClientBase<FE.WSDivisas.WSDivisasSoap>, FE.WSDivisas.WSDivisasSoap {
        
        public WSDivisasSoapClient() {
        }
        
        public WSDivisasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDivisasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDivisasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDivisasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FE.WSDivisas.RecuperarCotizacionResponse FE.WSDivisas.WSDivisasSoap.RecuperarCotizacion(FE.WSDivisas.RecuperarCotizacionRequest request) {
            return base.Channel.RecuperarCotizacion(request);
        }
        
        public string RecuperarCotizacion(string moneda) {
            FE.WSDivisas.RecuperarCotizacionRequest inValue = new FE.WSDivisas.RecuperarCotizacionRequest();
            inValue.Body = new FE.WSDivisas.RecuperarCotizacionRequestBody();
            inValue.Body.moneda = moneda;
            FE.WSDivisas.RecuperarCotizacionResponse retVal = ((FE.WSDivisas.WSDivisasSoap)(this)).RecuperarCotizacion(inValue);
            return retVal.Body.RecuperarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FE.WSDivisas.RecuperarCotizacionResponse> FE.WSDivisas.WSDivisasSoap.RecuperarCotizacionAsync(FE.WSDivisas.RecuperarCotizacionRequest request) {
            return base.Channel.RecuperarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FE.WSDivisas.RecuperarCotizacionResponse> RecuperarCotizacionAsync(string moneda) {
            FE.WSDivisas.RecuperarCotizacionRequest inValue = new FE.WSDivisas.RecuperarCotizacionRequest();
            inValue.Body = new FE.WSDivisas.RecuperarCotizacionRequestBody();
            inValue.Body.moneda = moneda;
            return ((FE.WSDivisas.WSDivisasSoap)(this)).RecuperarCotizacionAsync(inValue);
        }
    }
}
